###
@baseUrl = https://localhost:8010/banking/v2
@authServer = https://localhost:7010

@devClientId = dev-token-client

@email = erika.mustermann@t-online.de
@password = Geh1m_
@accountType = customer

@apiScope = banking_api

@id = 10000000-0000-0000-0000-000000000000
@firstname = Erika
@lastname = Mustermann
@companyName = null

### 
# @name 1) Create Customer on IA-Provider (Dev-only)
POST {{authServer}}/dev/users
Content-Type: application/json
Accept: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "confirmPassword": "{{password}}",
  "accountType": "{{accountType}}",
  "adminRights": 0,
  "mustChangePassword": false
}

> {%
    client.test("IA-Server: Employee created", function() {
        client.assert(response.status === 201, "Expected HTTP 201");
    });
%}

### 
# @name 2) Get a bearer token scope=openid profile offline_access {{apiScope}}
POST {{authServer}}/connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=dev_password
    &client_id={{devClientId}}
    &email={{email}}
    &password={{password}}
    &scope={{apiScope}}

> {%
    client.test("Employee token created", function() {
        client.assert(response.status === 200, "Expected HTTP 200");
        client.assert(!!response.body.access_token, "Missing access_token");
    });

    client.global.set("accessToken", response.body.access_token);
%}

###
# @name 3) Post customer provision
POST {{baseUrl}}/customers/me/provision?id={{id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

###
# @name 4) Put customer profile
PUT {{baseUrl}}/customers/me/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "{{id}}",
  "firstname": "{{firstname}}",
  "lastname": "{{lastname}}",
  "companyName": null,
  "email": "{{email}}",
  "subject": "xxxx",
  "statusInt": 1,
  "addressDto": {
    "street": "Hauptstr. 23",
    "postalCode": "29556",
    "city": "Suderburg",
    "country": "DE"
  }
}

###
# @name 4) Add first account this customer
POST {{baseUrl}}/customers/{{id}}/accounts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "01000000-0000-0000-0000-000000000000",
  "iban": "DE10 1000 0000 0000 0000 42",
  "balance": 2100,
  "currency": 1,
  "customerId": "{{id}}"
}
