
###
# @name Post employee1
POST {{authServer}}/dev/token
Content-Type: application/json
Accept: application/json

{
  "Email": "admin@mail.local",
  "Password":"Geh1m_",
  "Api": "BankingApi"
}

> {%
const body = response.body;
client.global.set("accessToken", body.access_token || body.token || body.accessToken);
%}


###
# @name Post employee2
POST {{baseUrl}}/employees
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "00000000-0002-0000-0000-000000000000",
  "firstname": "Walter",
  "lastname": "Wagner",
  "email": "w.wagner@banking.de",
  "phone": "+49 5826 123 4020",
  "subject": "11111111-0002-0000-0000-000000000000",
  "adminrights": 511,
  "personnelnumber": "Emp002"
}

###
# @name Post employee Admin
POST {{baseUrl}}/employees
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "00000000-0099-0000-0000-000000000000",
  "firstname": "Anonymous",
  "lastname": "Admin",
  "email": "admin@mail.local",
  "phone": "+49 5826 123 4099",
  "subject": "11111111-0099-0000-0000-000000000000",
  "adminrights": 255,
  "personnelnumber": "Emp099"
}
